# Generated by Django 6.0.2 on 2026-04-18 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customerprofile_latitude_customerprofile_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerBankDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bank', 'Bank'), ('upi', 'UPI')], max_length=10)),
                ('account_holder_name', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('upi_id', models.CharField(blank=True, max_length=100)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='accounts.farmerprofile')),
            ],
        ),
    ]
