# Generated by Django 6.0.2 on 2026-04-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_farmerbankdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('farmer', 'Farmer'), ('customer', 'Customer'), ('delivery_partner', 'Delivery Partner'), ('admin', 'Admin')], max_length=20),
        ),
    ]
