# Generated by Django 6.0.2 on 2026-04-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_payment_status_order_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='reserved_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
